# Generated by Django 4.2 on 2024-11-21 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('department', models.CharField(max_length=32, verbose_name='Department')),
                ('status', models.IntegerField(choices=[(1, 'On Hold'), (2, 'In Progress'), (3, 'Stopped'), (4, 'Finished')], default=1, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
